config/routes.rb
Rails.application.routes.draw do

  root "restaurantes#index"

  resources :comentarios

  resources :qualificacoes

  resources :clientes

  VotaPrato::Application.routes.draw do
  resources :comentarios

  resources :qualificacoes

  resources :clientes

    match 'Ola' => 'ola_mundo#index', via: 'get'
  end

  resources :restaurantes do
    resources :qualificacoes
  end

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base

	has_many :qualificacoes
	has_and_belongs_to_many :pratos
	

	validates_presence_of :nome, message: " - deve ser preenchido"

	validates_uniqueness_of :nome, message: " - nome já cadastrado"

	validates_numericality_of :idade, greater_than: 0,
                                  less_than: 100,
                                  message: " - deve ser um número entre 0 e 100"
end

app/models/prato.rb
class Prato < ActiveRecord::Base

	has_and_belongs_to_many :restaurantes
	has_one :receita

	validates_presence_of :nome, message: " - deve ser preenchido"
	validates_uniqueness_of :nome, message: " - nome já cadastrado"

	validate :validates_presence_of_more_than_one_restaurante

	private
	def validate_presence_of_more_than_one_restaurante
		errors.add("restaurantes","deve haver ao menos um restaurante") if restaurantes.isEmpty?
	end


end

app/models/qualificacao.rb
class Qualificacao < ActiveRecord::Base

	belongs_to :cliente
	belongs_to :restaurante

	has_many :comentarios, as: :comentavel
	
	validates_presence_of :cliente_id, :restaurante_id
	validates_associated :cliente, :restaurante

	validates_presence_of :nota, message: " - deve ser preenchido"
	validates_presence_of :valor_gasto, message: " - deve ser preenchido"

	validates_numericality_of :nota, greater_than_or_equal_to: 0,
                                less_than_or_equal_to: 10,
                                message: " - deve ser um número entre 0 e 10"

	validates_numericality_of :valor_gasto, greater_than: 0,
                                        message: " - deve ser um número maior que 0"
end

app/models/receita.rb
class Receita < ActiveRecord::Base

	belongs_to :prato
	validates_presence_of :conteudo, message: " - deve ser preenchido"
	validates_presence_of :prato_id
	validates_associated :prato

end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
	
	has_many :qualificacoes

	has_many :comentarios, as: :comentavel


	validates_presence_of :nome, message: "deve ser preenchido"
	validates_presence_of :endereco, message: "deve ser preenchido"
	validates_presence_of :especialidade, message: "deve ser preenchido"

	validates_uniqueness_of :nome, message: "nome já cadastrado"
	validates_uniqueness_of :endereco, message: "endereço já cadastrado"

	validate :validates_primeira_letra_deve_ser_maiuscula

	has_attached_file :foto, styles: 
	{ medium: "300x300>", thumb: "100x100>"}

	private
	def validates_primeira_letra_deve_ser_maiuscula
		errors.add(:nome,"A primeira letra deve ser maiuscula") unless nome =~ /[A-Z].*/
	end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
	def index
		@restaurantes = Restaurante.order("nome").page(params['page']).per(2)
		respond_to do |format| 
			format.xml {render xml: @restaurantes}
			format.json {render json: @restaurantes}						
			format.html 
		end
	end

	def create
		@restaurante = Restaurante.new(restaurante_params)
		if @restaurante.save
			redirect_to action: "show", id: @restaurante
		else
			render action: "new"
		end
	end

	def edit
		@restaurante = Restaurante.find(params[:id])
	end

	def update
		@restaurante = Restaurante.find params[:id]
		if @restaurante.update_attributes restaurante_params
			redirect_to action: "show", id: @restaurante
		else
			render action: "edit"
		end
	end

	def restaurante_params
		params.require(:restaurante).permit(:nome,:endereco,:especialidade, :foto)
	end

	def show
		@restaurante = Restaurante.find(params[:id])

		respond_to do |format| 
			format.xml {render xml: @restaurante}
			format.json {render json: @restaurante}						
			format.html 
		end
	end

	def destroy
		@restaurante = Restaurante.find(params[:id])
		@restaurante.destroy
		redirect_to(action: "index")		
	end

	def new
		@restaurante = Restaurante.new
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def valor_formatado(number)
		number_to_currency number,
			unit: "R$",
			separator: ",",
			delimiter: "."
	end

	def novo_comentario(comentavel)
		render partial: "comentarios/novo_comentario",
			   locals: {comentavel: comentavel}
	end	

	def comentarios(comentavel)
		render partial: "comentarios/comentarios",
			locals: {comentarios: comentavel.comentarios}
	end	

	def menu_principal(controllers)
		render partial: "layouts/menu_principal", locals: {opcoes: controllers}
	end

end

app/helpers/ola_mundo_helper.rb
module OlaMundoHelper
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VotaPrato</title>
  <%= stylesheet_link_tag 'scaffold'%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= menu_principal  %w(restaurantes clientes qualificacoes) %>


 <div id="main-container" class="container-fluid">
      <div class="row">
        <div id="sidebar" class="col-xs-3">
        <h3>Como bem, coma certo!</h3>
        </div>
        <div id="main-content" class="col-xs-9">
        <%= yield %>
        </div>
      </div>
    </div>

<script type="text/javascript">
	<%= yield :js %>
</script>

</body>
</html>

app/views/restaurantes/_form.html.erb
<%= form_for(@restaurante, html: {class: 'form-horizontal'}) do |f| %>
  <% if @restaurante.errors.any? %>
    <div id="error_explanation">
	<h2>%= pluralize(@restaurante.errors.count, "error") % problema(s) ao salvar</h2>
		<ul>
			<% @restaurante.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
   </div>
<% end %>
	
	<div class="field form-group">
		<%= f.label :nome, class: 'col-sm-2 control-label' %> 
		<div class="col-sm-10">
			<%= f.text_field :nome, class: 'form-control' %><br/>
		</div>	
	</div>
	
	<div class="field form-group">
		<%= f.label :endereco, class: 'col-sm-2 control-label' %> 
		<div class="col-sm-10">
			<%= f.text_field :endereco, class: 'form-control' %><br/>
		</div>	
	</div>	

	<div class="field form-group">
		<%= f.label :especialidade, class: 'col-sm-2 control-label' %> 
		<div class="col-sm-10">
			<%= f.text_field :especialidade, class: 'form-control' %><br/>
		</div>	
	</div>
	<div class="field form-group">
		<%= f.label :foto, class:'col-sm-2 control-label' %>
		<div class="col-lg-10">
			<%= f.file_field :foto, class: 'form-control' %><br/>
		</div>	
	</div>

	<div class="field form-group">
    	<div class="col-sm-offset-2 col-sm-10">
      		<%= f.submit class: "btn btn-default"%>
    	    <%= link_to 'Voltar', action:'index',class: 'btn btn-link' %>
    	</div>
  	</div>

	</div>
<% end %>	

app/views/restaurantes/edit.html.erb
<%= render partial: "form" %>

app/views/restaurantes/index.html.erb
<table class="table">
	<tr>
		<th>Id</th>
		<th>Nome</th>
		<th>Endereço</th>
		<th>Especialidade</th>
	</tr>
	<% @restaurantes.each do |r|  %>
	<tr>
		<td><%= r.id %></td>
		<td><%= r.nome %></td>
		<td><%= r.endereco %></td>
		<td><%= r.especialidade %></td>
		<td><%= link_to 'Exibir',r, action: 'show',class: 'btn btn-info btn-xs' %></td>
		<td><%= link_to 'Editar', edit_restaurante_path(r), class: 'btn btn-warning btn-xs' %></td>
		<td><%= link_to 'Deletar',r, method: :delete, data: { confirm: 'Vocẽ tem certeza?' },class: 'btn btn-danger btn-xs'%></td>
	</tr>
	<% end %>
</table>
<%= paginate @restaurantes %>
<br />
<%= link_to new_restaurante_path, class: 'btn btn-success btn-lg' do %>	
	<i class="glypgicon glyphicon-plus"></i>Novo
<% end %>

app/views/restaurantes/new.html.erb
<%= form_for @restaurante do |f| %>
	Nome: <%= f.text_field :nome %><br/>
	Endereco: <%= f.text_field :endereco %><br/>
	Especialidade: <%= f.text_field :especialidade %><br/>
 <%= f.submit %>
<% end %>	

app/views/restaurantes/show.html.erb
<h1>Exibindo Restaurantes</h1>

<p>
	<b>Nome: </b>
	<%= @restaurante.nome %>
</p>	
<p>
	<b>Endereço: </b>
	<%= @restaurante.endereco %>
</p>
<p>
	<b>Especialidade: </b> 
	<%= @restaurante.especialidade %>
</p>
<b>Nota média: </b>
	<%= @restaurante.qualificacoes.average(:nota)%><br />
<b>Qualificações: </b>
	<%= @restaurante.qualificacoes.count(:nota)%><br />
<b>Preço médio: </b>
	<%= @restaurante.qualificacoes.average(:valor_gasto)%><br /><br />

 
 <%= link_to 'Editar', action:'edit', id: @restaurante %>
 <%= link_to 'Voltar', action:'index' %>

<%= comentarios @restaurante %>
<%= novo_comentario @restaurante %>
<p>
	<b>Foto:</b>
	  <%= image_tag @restaurante.foto.url(:thumb) %>
</p>